variables:
  APP_RELEASE_NAME: cubejs-deployment
  APP_REGISTRY_IMAGE: 192.168.99.105:5000/cubejs-deployment:$CI_COMMIT_REF_SLUG

services:
  - lordgaav/dind-options:latest

stages:
  - package
  - staging
  - production

package:
  stage: package
  image: docker:latest
  variables:
    DOCKER_OPTS: "--insecure-registry=192.168.99.105:5000"
#    DOCKER_HOST: "tcp://lordgaav__dind-options:2375"
#     https://github.com/LordGaav/dind-options
  tags:
    - staging
  script:
    - echo Build Docker image $APP_REGISTRY_IMAGE
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD http://192.168.99.105:5000
    - docker build -t $APP_REGISTRY_IMAGE ./cubejs-deployment/.
    - docker push $APP_REGISTRY_IMAGE
  only:
    - staging

deploy:
  stage: staging
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - staging
  dependencies: []
  script:
    - echo Deploy Helm release cubejs-deployment
    - helm upgrade --install --namespace=staging --set image.tag=$CI_COMMIT_REF_SLUG $APP_RELEASE_NAME ./cubejs-deployment/charts/cubejs-deployment
  only:
    - staging

remove:
  stage: staging
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - staging
  dependencies: []
  script:
    - echo Delete Helm release cubejs-deployment
    - /helm delete --purge cubejs-deployment
  only:
    - staging
  when: manual

deploy-production:
  stage: production
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - production
  dependencies: []
  script:
    - echo Deploy Helm release cubejs-deployment
    - helm upgrade \
      --install \
      --namespace=production \
      --set image.tag=$CI_COMMIT_REF_SLUG \
      cubejs-deployment \
      ./cubejs-deployment/charts/cubejs-deployment
  only:
    - staging
  when: manual
