variables:
  APP_RELEASE_NAME: superads-sdk-reports
  APP_REGISTRY_IMAGE: superads-sdk-reports:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

stages:
  - package
  - staging
  - production

package:
  stage: package
  image: docker:latest
  tags:
    - staging
  script:
    - echo Build Docker image $APP_REGISTRY_IMAGE
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD http://192.168.99.105:5000
    - docker build -t $APP_REGISTRY_IMAGE ./superads-sdk-reports-api/.
    - docker push http://192.168.99.105:5000/$APP_REGISTRY_IMAGE
  only:
    - staging

deploy:
  stage: staging
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - staging
  dependencies: []
  script:
    - echo Deploy Helm release superads-sdk-reports
    - helm upgrade --install --namespace=staging --set image.tag=$CI_COMMIT_REF_SLUG $APP_RELEASE_NAME ./superads-sdk-reports-api/charts/superads-sdk-reports
  only:
    - staging

remove:
  stage: staging
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - staging
  dependencies: []
  script:
    - echo Delete Helm release superads-sdk-reports
    - /helm delete --purge superads-sdk-reports
  only:
    - staging
  when: manual

deploy-production:
  stage: production
  image:
    name: alpine/helm
    entrypoint: [/bin/sh]
  tags:
    - production
  dependencies: []
  script:
    - echo Deploy Helm release superads-sdk-reports
    - helm upgrade \
      --install \
      --namespace=production \
      --set image.tag=$CI_COMMIT_REF_SLUG \
      superads-sdk-reports \
      ./superads-sdk-reports-api/charts/superads-sdk-reports
  only:
    - staging
  when: manual
