replicaCount: 1

image:
  repository: registry.gitlab.com/superads-sdk/superads-sdk-reports
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 4000
