replicaCount: 1

image:
  repository: registry.gitlab.com/yohayg-demo/superads-sdk-reports
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 4000
